symbols = [
  "IIFL.NS", "BANDHANBNK.NS", "MCX.NS", "MANAPPURAM.NS", "MGL.NS", "RBLBANK.NS", "IREDA.NS", "HINDZINC.NS", "OFSS.NS", "BANKINDIA.NS",
  "LAURUSLABS.NS", "INDIGO.NS", "MUTHOOTFIN.NS", "BHARATFORG.NS", "IEX.NS", "JIOFIN.NS", "CHOLAFIN.NS", "KOTAKBANK.NS", "JSL.NS", "PFC.NS",
  "AUBANK.NS", "M&MFIN.NS", "ABCAPITAL.NS", "IRB.NS", "TATACHEM.NS", "INDIANB.NS", "ABB.NS", "RECLTD.NS", "KPITTECH.NS", "SIEMENS.NS",
  "HDFCAMC.NS", "BAJFINANCE.NS", "TATAELXSI.NS", "BIOCON.NS", "NYKAA.NS", "SBICARD.NS", "POONAWALLA.NS", "FEDERALBNK.NS", "TRENT.NS", "JSWENERGY.NS",
  "OIL.NS", "TATATECH.NS", "PPLPHARMA.NS", "MPHASIS.NS", "MAXHEALTH.NS", "MOTHERSON.NS", "CHAMBLFERT.NS", "SONACOMS.NS", "VEDL.NS", "AXISBANK.NS"
];
