
symbols = [
  "WCIL.NS", "TVTODAY.NS", "EIHAHOTELS.NS", "PARAGMILK.NS", "MATRIMONY.NS", "THANGAMAYL.NS", "SSWL.NS", "BOROLTD.NS", "KIRIINDUS.NS", "NFL.NS",
  "TFCILTD.NS", "AVTNPL.NS", "AXITA.NS", "BHAGYANGR.NS", "BYKE.NS", "CINELINE.NS", "CORDSCABLE.NS", "ELDEHSG.NS", "GRMOVER.NS", "GULFPETRO.NS",
  "IMPAL.NS", "KINGFA.NS", "KMSUGAR.NS", "MOTOGENFIN.NS", "NITCO.NS", "RANASUG.NS", "SOMATEX.NS", "SREEL.NS", "STEELCAS.NS", "TREEHOUSE.NS",
]